-- ============================================================
-- PW2M CRIANÇA NFC - SUPABASE / POSTGRESQL
-- 01 - ESTRUTURA PRINCIPAL
-- ============================================================

create extension if not exists pgcrypto;

-- Perfil do responsável (1:1 com auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Crianças pertencentes ao responsável autenticado
create table if not exists public.children (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,

  -- Token público permanente gravado no NFC.
  -- Não usar o ID sequencial/interno na URL pública.
  public_token uuid not null unique default gen_random_uuid(),

  full_name text not null,
  birth_date date,
  blood_type text check (
    blood_type is null or blood_type in ('A+','A-','B+','B-','AB+','AB-','O+','O-')
  ),
  photo_url text,

  -- Endereço existe no cadastro, mas NÃO será retornado na função pública.
  address_line text,
  city text,
  state char(2),

  public_enabled boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_children_owner_id on public.children(owner_id);
create index if not exists idx_children_public_token on public.children(public_token);

-- Contatos dos responsáveis
create table if not exists public.emergency_contacts (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,

  name text not null,
  relation_label text not null,
  phone text not null,
  whatsapp text,
  priority smallint not null default 1,

  created_at timestamptz not null default now()
);

create index if not exists idx_emergency_contacts_child_id
  on public.emergency_contacts(child_id);

-- Informações médicas / de emergência
create table if not exists public.medical_info (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null unique references public.children(id) on delete cascade,

  allergies text,
  conditions_text text,
  medications text,
  health_plan text,
  health_plan_number text,
  emergency_notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tags/dispositivos NFC adicionais.
-- O link principal pode usar children.public_token.
create table if not exists public.nfc_devices (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,

  device_name text not null,
  device_token uuid not null unique default gen_random_uuid(),
  active boolean not null default true,

  created_at timestamptz not null default now()
);

create index if not exists idx_nfc_devices_child_id
  on public.nfc_devices(child_id);

-- Histórico simples de leitura do NFC.
-- É opcional utilizar esta tabela no MVP.
create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  child_id uuid not null references public.children(id) on delete cascade,
  device_id uuid references public.nfc_devices(id) on delete set null,
  accessed_at timestamptz not null default now()
);

create index if not exists idx_access_logs_child_date
  on public.access_logs(child_id, accessed_at desc);

-- ============================================================
-- ATUALIZAÇÃO AUTOMÁTICA DE updated_at
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_children_updated_at on public.children;
create trigger trg_children_updated_at
before update on public.children
for each row execute function public.set_updated_at();

drop trigger if exists trg_medical_info_updated_at on public.medical_info;
create trigger trg_medical_info_updated_at
before update on public.medical_info
for each row execute function public.set_updated_at();

-- ============================================================
-- CRIA PERFIL QUANDO UM USUÁRIO É CRIADO NO SUPABASE AUTH
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();
