-- ============================================================
-- PW2M CRIANÇA NFC - SUPABASE / POSTGRESQL
-- 01 - ESTRUTURA PRINCIPAL
-- ============================================================

create extension if not exists pgcrypto;

-- Perfil do responsável (1:1 com auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Crianças pertencentes ao responsável autenticado
create table if not exists public.children (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,

  -- Token público permanente gravado no NFC.
  -- Não usar o ID sequencial/interno na URL pública.
  public_token uuid not null unique default gen_random_uuid(),

  full_name text not null,
  birth_date date,
  blood_type text check (
    blood_type is null or blood_type in ('A+','A-','B+','B-','AB+','AB-','O+','O-')
  ),
  photo_url text,

  -- Endereço existe no cadastro, mas NÃO será retornado na função pública.
  address_line text,
  city text,
  state char(2),

  public_enabled boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_children_owner_id on public.children(owner_id);
create index if not exists idx_children_public_token on public.children(public_token);

-- Contatos dos responsáveis
create table if not exists public.emergency_contacts (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,

  name text not null,
  relation_label text not null,
  phone text not null,
  whatsapp text,
  priority smallint not null default 1,

  created_at timestamptz not null default now()
);

create index if not exists idx_emergency_contacts_child_id
  on public.emergency_contacts(child_id);

-- Informações médicas / de emergência
create table if not exists public.medical_info (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null unique references public.children(id) on delete cascade,

  allergies text,
  conditions_text text,
  medications text,
  health_plan text,
  health_plan_number text,
  emergency_notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tags/dispositivos NFC adicionais.
-- O link principal pode usar children.public_token.
create table if not exists public.nfc_devices (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,

  device_name text not null,
  device_token uuid not null unique default gen_random_uuid(),
  active boolean not null default true,

  created_at timestamptz not null default now()
);

create index if not exists idx_nfc_devices_child_id
  on public.nfc_devices(child_id);

-- Histórico simples de leitura do NFC.
-- É opcional utilizar esta tabela no MVP.
create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  child_id uuid not null references public.children(id) on delete cascade,
  device_id uuid references public.nfc_devices(id) on delete set null,
  accessed_at timestamptz not null default now()
);

create index if not exists idx_access_logs_child_date
  on public.access_logs(child_id, accessed_at desc);

-- ============================================================
-- ATUALIZAÇÃO AUTOMÁTICA DE updated_at
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_children_updated_at on public.children;
create trigger trg_children_updated_at
before update on public.children
for each row execute function public.set_updated_at();

drop trigger if exists trg_medical_info_updated_at on public.medical_info;
create trigger trg_medical_info_updated_at
before update on public.medical_info
for each row execute function public.set_updated_at();

-- ============================================================
-- CRIA PERFIL QUANDO UM USUÁRIO É CRIADO NO SUPABASE AUTH
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();



-- ============================================================
-- PW2M CRIANÇA NFC
-- 02 - ROW LEVEL SECURITY
-- ============================================================

alter table public.profiles enable row level security;
alter table public.children enable row level security;
alter table public.emergency_contacts enable row level security;
alter table public.medical_info enable row level security;
alter table public.nfc_devices enable row level security;
alter table public.access_logs enable row level security;

-- ------------------------------------------------------------
-- PROFILES
-- ------------------------------------------------------------

drop policy if exists "profile_select_own" on public.profiles;
create policy "profile_select_own"
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "profile_update_own" on public.profiles;
create policy "profile_update_own"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- ------------------------------------------------------------
-- CHILDREN
-- ------------------------------------------------------------

drop policy if exists "children_select_own" on public.children;
create policy "children_select_own"
on public.children
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists "children_insert_own" on public.children;
create policy "children_insert_own"
on public.children
for insert
to authenticated
with check (owner_id = auth.uid());

drop policy if exists "children_update_own" on public.children;
create policy "children_update_own"
on public.children
for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists "children_delete_own" on public.children;
create policy "children_delete_own"
on public.children
for delete
to authenticated
using (owner_id = auth.uid());

-- ------------------------------------------------------------
-- EMERGENCY_CONTACTS
-- ------------------------------------------------------------

drop policy if exists "contacts_select_own" on public.emergency_contacts;
create policy "contacts_select_own"
on public.emergency_contacts
for select
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "contacts_insert_own" on public.emergency_contacts;
create policy "contacts_insert_own"
on public.emergency_contacts
for insert
to authenticated
with check (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "contacts_update_own" on public.emergency_contacts;
create policy "contacts_update_own"
on public.emergency_contacts
for update
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "contacts_delete_own" on public.emergency_contacts;
create policy "contacts_delete_own"
on public.emergency_contacts
for delete
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

-- ------------------------------------------------------------
-- MEDICAL_INFO
-- ------------------------------------------------------------

drop policy if exists "medical_select_own" on public.medical_info;
create policy "medical_select_own"
on public.medical_info
for select
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "medical_insert_own" on public.medical_info;
create policy "medical_insert_own"
on public.medical_info
for insert
to authenticated
with check (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "medical_update_own" on public.medical_info;
create policy "medical_update_own"
on public.medical_info
for update
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "medical_delete_own" on public.medical_info;
create policy "medical_delete_own"
on public.medical_info
for delete
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

-- ------------------------------------------------------------
-- NFC_DEVICES
-- ------------------------------------------------------------

drop policy if exists "nfc_select_own" on public.nfc_devices;
create policy "nfc_select_own"
on public.nfc_devices
for select
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "nfc_insert_own" on public.nfc_devices;
create policy "nfc_insert_own"
on public.nfc_devices
for insert
to authenticated
with check (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "nfc_update_own" on public.nfc_devices;
create policy "nfc_update_own"
on public.nfc_devices
for update
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

drop policy if exists "nfc_delete_own" on public.nfc_devices;
create policy "nfc_delete_own"
on public.nfc_devices
for delete
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);

-- ------------------------------------------------------------
-- ACCESS_LOGS
-- Responsável consegue consultar os acessos das próprias crianças.
-- O INSERT público será feito apenas por uma RPC segura.
-- ------------------------------------------------------------

drop policy if exists "logs_select_own" on public.access_logs;
create policy "logs_select_own"
on public.access_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.children c
    where c.id = child_id
      and c.owner_id = auth.uid()
  )
);



-- ============================================================
-- PW2M CRIANÇA NFC
-- 03 - FUNÇÕES PÚBLICAS SEGURAS
-- ============================================================
--
-- IMPORTANTE:
-- Não damos SELECT público direto nas tabelas.
-- A pessoa que encosta o celular no NFC chama esta função
-- passando o token da criança.
--
-- A função devolve SOMENTE o conteúdo permitido.
-- Endereço, e-mail, IDs internos e dados administrativos não são
-- devolvidos.
-- ============================================================

create or replace function public.get_public_child(p_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'name', c.full_name,

    -- Retorna idade, não a data exata de nascimento.
    'age_years',
      case
        when c.birth_date is null then null
        else extract(year from age(current_date, c.birth_date))::int
      end,

    'blood_type', c.blood_type,
    'photo_url', c.photo_url,

    'medical', jsonb_build_object(
      'allergies', mi.allergies,
      'conditions', mi.conditions_text,
      'medications', mi.medications,
      'health_plan', mi.health_plan,
      'health_plan_number', mi.health_plan_number,
      'emergency_notes', mi.emergency_notes
    ),

    'contacts',
      coalesce(
        (
          select jsonb_agg(
            jsonb_build_object(
              'name', ec.name,
              'relation', ec.relation_label,
              'phone', ec.phone,
              'whatsapp', ec.whatsapp
            )
            order by ec.priority, ec.created_at
          )
          from public.emergency_contacts ec
          where ec.child_id = c.id
        ),
        '[]'::jsonb
      )
  )
  from public.children c
  left join public.medical_info mi
    on mi.child_id = c.id
  where c.public_token = p_token
    and c.public_enabled = true
  limit 1;
$$;

-- Só as funções necessárias ficam executáveis publicamente.
revoke all on function public.get_public_child(uuid) from public;
grant execute on function public.get_public_child(uuid) to anon, authenticated;

-- ============================================================
-- RPC OPCIONAL PARA REGISTRAR ACESSO À FICHA
-- ============================================================

create or replace function public.log_public_child_access(p_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_child_id uuid;
begin
  select id into v_child_id
  from public.children
  where public_token = p_token
    and public_enabled = true
  limit 1;

  if v_child_id is null then
    return false;
  end if;

  insert into public.access_logs(child_id)
  values (v_child_id);

  return true;
end;
$$;

revoke all on function public.log_public_child_access(uuid) from public;
grant execute on function public.log_public_child_access(uuid) to anon, authenticated;
